nowandthen/urls.py
from django.urls import path
from nowandthen import views

app_name = 'nowandthen'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('add_picture/', views.add_picture, name='add_picture'),
    path('search/', views.search_results, name='search_results'),
    path('photos/', views.search_results, name='photos'),
    path('1970/', views.photo70_list, name='1970'),
    path('1980/', views.photo80_list, name='1980'),
    path('2010/', views.photo10_list, name='2010'),
    path('photo_feed/', views.photo_feed, name='photo_feed'),
]

nowandthen_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from nowandthen import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', views.index, name='index'),
                  path('nowandthen/', include('nowandthen.urls')),
                  path('/', views.image_detail, name='image_detail'),
                  # The above maps any URLs starting with nowandthen/ to be handled by nowandthen.
                  path(r'^oauth/', include('social_django.urls', namespace='social')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nowandthen/forms.py
from django import forms
from nowandthen.models import Page, Category, Picture, Comment
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.models import User
from nowandthen.models import UserProfile


ERA_CHOICES= [
    ('Present_day', 'Present Day'),
    ('2010-2020', '2010-2020'),
    ('2000-2010', '2000-2010'),
    ('1990s', '1990s'),
    ('1980s', '1980s'),
    ('1970s', '1970s'),
    ('1960s and earlier', '1960s and earlier')
    ]

class PictureForm(forms.ModelForm):
    title = forms.CharField(help_text="What is your picture's title?",widget=forms.TextInput(attrs={'size': '170'}), required=True)
    description = forms.CharField(help_text="Please tell us about a bit about your picture.", widget=forms.Textarea(), required=True)
    tag_one = forms.CharField(help_text="Please provide a word to describe your image. This will help people to find it.", required=False)
    tag_two = forms.CharField(help_text="Please give us an additional word to describe the picture.", required=False)
    era = forms.CharField(help_text="What era does this picture relate to?",widget=forms.Select(choices=ERA_CHOICES), required=True)
    #slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    image = forms.ImageField()
    class Meta:
        model = Picture
        fields = ('image', 'title', 'description', 'tag_one', 'tag_two','era',)
    def as_p(self):
        #Returns this form rendered as HTML <p>s.
        return self._html_output(
            normal_row='<p%(help_text)s<p></p>%(field)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True)   
 
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class CategoryForm(forms.ModelForm):
    name = forms.CharField(help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

# An inline class to provide additional information on the form.
    class Meta:
# Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    class Meta:
    # Provide an association between the ModelForm and a model
        model = Page
    # What fields do we want to include in our form?
    # This way we don't need every field in the model present.
    # Some fields may allow NULL values; we may not want to include them.
    # Here, we are hiding the foreign key.
    # we can either exclude the category field from the form,
        exclude = ('category',)
    # or specify the fields to include (don't include the category field).
    #fields = ('title', 'url', 'views')
        def clean(self):
            cleaned_data = self.cleaned_data
            url = cleaned_data.get('url')
            # If url is not empty and doesn't start with 'http://',
            # then prepend 'http://'.
            if url and not url.startswith('http://'):
                url = f'http://{url}'
                cleaned_data['url'] = url
            return cleaned_data
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

 

nowandthen/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.db.models import Q
from pip._vendor.requests import post

from nowandthen.models import Category
from nowandthen.models import Page
from nowandthen.models import Picture
from nowandthen.forms import CategoryForm
from nowandthen.forms import PictureForm
from nowandthen.forms import CommentForm
from django.shortcuts import redirect
from django.urls import reverse
from nowandthen.forms import PageForm
from nowandthen.forms import UserForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login, logout
from datetime import datetime


# Method adapted from https://stackoverflow.com/questions/45226024/how-can-i-make-categories-in-a-image-gallery-in-django?fbclid=IwAR2-p5CeVAdPdpiYCJTDRlCW5-M_0AOMmKNygNBoEpv6v498Km8sySuFO3o

def photo_list(request):
    queryset = Picture.objects.all()
    context = {
        "photos": queryset,
    }
    return render(request, 'nowandthen/photos.html', context)


def photo70_list(request):
    queryset = Picture.objects.all()
    context = {
        "photos": queryset,
    }
    return render(request, 'nowandthen/1970.html', context)


def photo80_list(request):
    queryset = Picture.objects.all()
    context = {
        "photos": queryset,
    }
    return render(request, 'nowandthen/1980.html', context)


def photo10_list(request):
    queryset = Picture.objects.all()
    context = {
        "photos": queryset,
    }
    return render(request, 'nowandthen/2010.html', context)


@login_required
def add_picture(request):
    form = PictureForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = PictureForm(request.POST, request.FILES)
        # Have we been provided with a valid form?
        if form.is_valid():
            form.save(commit=True)
            # Now that the category is saved, we could confirm this.
            # For now, just redirect the user back to the index view.
            return redirect(reverse('nowandthen:index'))
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)
    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'nowandthen/add_picture.html', {'form': form})


def photo_feed(request):
    picture_list = Picture.objects.order_by('when_added')

    context_dict = {}
    context_dict['pictures'] = picture_list

    return render(request, 'nowandthen/photo_feed.html', context=context_dict)


# To do with comments:

def image_detail(request, slug):
    template_name = 'image_detail.html'
    image = get_object_or_404(Picture, slug=slug)
    comments = image.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'image': image,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    visitor_cookie_handler(request)
    return render(request, 'nowandthen/index.html', context=context_dict)


def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'nowandthen/about.html', context=context_dict)


# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie
        # Update/set the visits cookie
        request.session['visits'] = visits


def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'nowandthen/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)
            # Now that the category is saved, we could confirm this.
            # For now, just redirect the user back to the index view.
            return redirect(reverse('nowandthen:index'))
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)
    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'nowandthen/add_category.html', {'form': form})


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()
            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()
            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user
            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            # Now we save the UserProfile model instance.
            profile.save()
            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()
        # Render the template depending on the context.
    return render(request,
                  'nowandthen/register.html',
                  context={'user_form': user_form,

templates/nowandthen/1970.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}

  {% block additional_styles %}
  <style>
   body{
    background-color:pink;
  }
  </style>
  {% endblock %}

{% block title_block %}
    1970ss
{% endblock %}

 {% block body_block %}
 <body>
    <div class="container text-center">
        1970s page currently under construction!
    </div>
</body>
 {% endblock %}

templates/nowandthen/1980.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}

  {% block additional_styles %}
  <style>
   body{
    background-color:pink;
  }
  </style>
  {% endblock %}

{% block title_block %}
    1980s
{% endblock %}

 {% block body_block %}
 <body>
    <div class="container text-center">
        1980s page currently under construction!
    </div>
</body>
 {% endblock %}

templates/nowandthen/2010.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}

  {% block additional_styles %}
  <style>
   body{
    background-color:pink;
  }
  </style>
  {% endblock %}

{% block title_block %}
    2010s
{% endblock %}

 {% block body_block %}
 <body>
    <div class="container text-center">
        2010s page currently under construction!
    </div>
</body>
 {% endblock %}

templates/nowandthen/about.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %} 
{% block title_block %}
About Rango
{% endblock %}
{% block body_block %}
<h1>Rango says...</h1>
<div>
here is the about page. <br />
<strong>This tutorial has been put
    together by Jeff Waters</strong><br />
<p> Visits: {{ visits }}</p>
</div>
<div>
<img src="{% static 'images/rango.jpg' %}"
alt="Picture of Rango" /> 
<br>
<img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a
Cat."/>
</div>
{% endblock %}

templates/nowandthen/add_page.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}
{% block title_block %}
Add a page
{% endblock %}
{% block body_block %}
<h1>Add a Page to {{ category.name }}</h1>
<div>
<form id="add_page_form" method="post" action="%url 'nowandthen:add_page' category.slug%">
{% csrf_token %}
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
 {% endfor %}
 {% for field in form.visible_fields %}
{{ field.errors }}
{{ field.help_text }}
{{ field }}
{% endfor %}
<input type="submit" name="submit" value="Add Page" />
</form>
 </div>
 {% endblock %}

templates/nowandthen/add_picture.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}
{% block title_block %}
Add self
{% endblock %}
{% block body_block %}
<h1>Add a Picture</h1>
<div>
<form id="picture_form" method="post" action="{% url 'nowandthen:add_picture' %}" enctype="multipart/form-data" >
{% csrf_token %}
{{ form.as_p }}
<input type="submit" name="submit" value="Add Picture" />
</form>
</div>
{% endblock %}

templates/nowandthen/categories.html
<ul>
{% if categories %}
{% for c in categories %}
{% if c == current_category %}
<li><strong><a href="{% url 'nowandthen:show_category' c.slug %}">{{ c.name }}</a></strong></li>
{% else %}
<li><a href="{% url 'nowandthen:show_category' c.slug %}">{{ c.name }}</a></li>
{% endif %}
{% endfor %}
{% else %}
<li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/nowandthen/category.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}
{% block title_block %}
{% if category %}
{{ category.name }}
{% else %}
Unknown Category
{% endif %}
{% endblock %}
{% block body_block %}
{% if category %}
<h1>{{ category.name }}</h1>
{% if pages %}
<ul>
{% for page in pages %}
<li><a href="{{ page.url }}">{{ page.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<strong>No pages currently in category.</strong>
{% endif %}
{% if user.is_authenticated %}
<a href="{% url 'nowandthen:add_page' category.slug %}">Add Page</a> <br />
{% endif %}
{% else %}
The specified category does not exist.
{% endif %}
{% endblock %}

templates/nowandthen/index.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}

  {% block additional_styles %}
  <style>
   body{
    background-image: url('/static/images/glasgow_cityscape.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
  </style>
  {% endblock %}

{% block title_block %}
    Homepage
{% endblock %}

 {% block body_block %}
 <body>
    <div class="container text-center">
        <div class="row h-100">
            <div class="col-sm-6">
                <p class="brownText">
                    <a href="{% url 'nowandthen:photo_feed' %}">View Pictures</a>
                </p>
            </div>
            <div class="col-sm-6">
                <p class="brownText"><a href="{% url 'nowandthen:add_picture' %}">Post Pictures</a></p>
            </div>
        </div>
    </div>
</body>
 {% endblock %}

templates/nowandthen/login.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}
<h1>Login to Now & Then</h1>
<form id="login_form" method="post" action="{% url 'nowandthen:login' %}">
{% csrf_token %}
Username: <input type="text" name="username" value="" size="50" />
<br />
Password: <input type="password" name="password" value="" size="50" />
<br />
<input type="submit" value="submit" />
</form>
 <br>
  <p><strong>-- OR --</strong></p>
  <a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a>
{% endblock %}

templates/nowandthen/photo_feed.html
{% extends 'nowandthen/base.html' %}

{% block body_block %}
<br>
<br>
<ul>
{% if pictures %}
    <ul>
    {% for p in pictures %}
        <li><img src="{{ MEDIA_URL }}shared_pics/{{ image }}"></li>
<!--        <li>{{ p.image.url }}</li>-->
    {% endfor %}
    </ul>
{% else %}
    <li><strong>There are no photographs present.</strong></li>
{% endif %}
</ul>
{% endblock %}

templates/nowandthen/photos.html
{% extends 'nowandthen/base.html' %}

{% block body_block %}
<br>
<br>
{% for photo in photos %}
<h1>{{ photo.title }}</h1>
{% if photo.image %}
<img src="{{ photo.image.url }}" class="img-responsive">
<img src="{{ some_object.image_field.url }}">
{% endif %}
{% endfor %}
{% endblock  %}

templates/nowandthen/restricted.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}
{% block title_block %}
Restricted Page
{% endblock %}
{% block body_block %}
Restricted page
{% endblock %}

templates/nowandthen/search_results.html
{% extends 'nowandthen/base.html' %}
{% load staticfiles %}

  {% block additional_styles %}
  <style>
   body{
    background-image: url('/static/images/glasgow_cityscape.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
  </style>
  {% endblock %}

{% block title_block %}
    Homepage
{% endblock %}

 {% block body_block %}
 <body>
    <div class="container text-center">
        <ul>
        {% for self in object_list %}
            <li>
                {{ self.image }}
            </li>
        {% endfor %}
        </ul>
    </div>
</body>
 {% endblock %}